#!/bin/sh

PATH=/bin:/usr/bin
export PATH

# Ensure the script is run as root
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

DEFAULT_PORT=8080
DEFAULT_API_KEY=hak_1234_foo
DEFAULT_API_URL=https://api.revenium.io

PACKAGE_REPO_KEYRING_FILE=rm-dev-archive-keyring.gpg
PACKAGE_REPO_LIST_FILE=rm-dev.list
PACKAGE_REPO_URL=https://pkg.dev.hcapp.io/deb

APT_SOURCES_LIST_DIR=/etc/apt/sources.list.d
KEYRING_DIR=/usr/share/keyrings

# Check if a port number is provided as an argument
if [ ${#} -ge 1 ]; then
    PORT="${1}"
else
    PORT="${DEFAULT_PORT}"
fi

# Check if an API key is provided as the second argument
if [ ${#} -ge 2 ]; then
    API_KEY="${2}"
else
    API_KEY="${DEFAULT_API_KEY}"
fi

# Check if API URL is provided as the third argument
if [ ${#} -ge 3 ]; then
    API_URL="${3}"
else
    API_URL="${DEFAULT_API_URL}"
fi

# Step 1: Update and install necessary packages
apt-get update && apt-get install -y curl lsb-release

# Step 2: Download the keyring for your package repository
curl -Lo "${KEYRING_DIR}/${PACKAGE_REPO_KEYRING_FILE}" \
    "${PACKAGE_REPO_URL}/${PACKAGE_REPO_KEYRING_FILE}"

# Step 3: Add your package repository to the sources list
printf "deb [signed-by=%s] %s/%s %s main\n" \
    "${KEYRING_DIR}/${PACKAGE_REPO_KEYRING_FILE}" \
    "${PACKAGE_REPO_URL}" \
    "$(lsb_release -is | tr A-Z a-z)" \
    "$(lsb_release -cs)" \
    > "${APT_SOURCES_LIST_DIR}/${PACKAGE_REPO_LIST_FILE}"

# Step 4: Update and install isotope and its eBPF shim
apt-get update && apt-get install -y isotope isotope-ebpf-shim

# Step 5: Run isotope with the specified parameters
nohup isotope \
    -port "${PORT}" \
    -api-key "${API_KEY}" \
    -platform-api-url "${API_URL}" \
    >> /var/log/isotope.log 2>&1 &
